name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: sayembillah-dev
          outputs: |
            dist/github-snake.svg?color_snake=%23F8990C&color_dots=%23E8EEF5,%23B9CBE0,%2389ABD6,%234DA2F5,%23208AEF
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%23F8990C&color_dots=%230B2A4C,%23103A63,%231C5A96,%23208AEF,%234DA2F5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
